sequenceDiagram
title "SQS Basic"

participant Sender
participant SQS
participant DQL
participant Consumer
    Note over Sender: SendMessage OR SendMessageBatch
    Sender ->> SQS : send messages (Message)
    SQS ->> Sender: response the result
    SQS ->> SQS: add message in the queue
    opt if queue is delayed queue
        SQS ->> SQS: wait for defined time (0-15min)
    end
    opt if message timer is set for the message
        SQS ->> SQS: wait for defined time (0-15min)
    end
    %% If both the queue-level delay and the message-level timer are used, the delays are additive. <br/> The max delay in total is 15 min.
    SQS ->> SQS: make the message visible
    Note over Consumer: ReceiveMessage
    Consumer ->> SQS: request a message
    opt if queue doesn't have messages AND wait time is defined
        %%  SQS: wait time setting is for long polling
        SQS ->> SQS: wait for newly coming messages for wait time
    end
    SQS ->> SQS: make the message invisible
    SQS ->> SQS: start the visibility time clock
    SQS ->> Consumer: return messages (Message, ReceiptHandle)
    Consumer ->> Consumer: handle the messages
    alt if the Consumer finish handling the messages BEFORE the time clock ends
        Note over Consumer: DeleteMessage OR DeleteMessageBatch
        Consumer ->> SQS: request to delete the messages (ReceiptHandle)
        SQS ->> SQS: delete the messages
        SQS ->> Consumer: return the result
    else if the time clock ends
        SQS ->> SQS: make messages again visible
    else if consumer request the message more than ${maxReceiveCount} times AND the time clock ends
        SQS ->> DQL: send message to DLQ (Message)
    end
